## <font color='blue'>PyTorch Assignment</font>

You have to implement ReLU, Softmax, and Neuron using PyTorch. Most probably, you have already implemented these functions using NumPy in the NumPy assignment. 

## <font color='blue'>Marking Scheme</font>

#### Maximum Points: 30

<div>
    <table>
        <tr><td><h3>Sr. no.</h3></td> <td><h3>Problem</h3></td> <td><h3>Points</h3></td> </tr>
        <tr><td><h3>1</h3></td> <td><h3>ReLU Implementation</h3></td> <td><h3>5</h3></td> </tr>
        <tr><td><h3>2</h3></td> <td><h3>Softmax Implementation</h3></td> <td><h3>10</h3></td> </tr>
        <tr><td><h3>3</h3></td> <td><h3>Neuron Implementation</h3></td> <td><h3>15</h3></td> </tr>
    </table>
</div>

In [ ]:
import torch

## <font color='blue'>1. ReLU Implementation (5 Points)</font>

**ReLU** stands for Rectified Linear Unit. It defined as follows:

```
z = max(0, x)
```


<img src='https://www.learnopencv.com/wp-content/uploads/2020/01/c3_w1_ReLU.png'/>

In this part, you have to implement this ReLU function definition for the NumPy array.

So if the input is:
```
tensor([[ 1.0000,  2.0000, -3.0000],
        [ 2.5000, -0.2000,  6.0000]])
```

You have to return the following output:
```
tensor([[1.0000, 2.0000, 0.0000],
        [2.5000, 0.0000, 6.0000]])
```

<div class="alert alert-block alert-info">
    <b>1. ReLU Implementation: 5 Points</b>
</div>

In [ ]:
def ReLU(tensor):
    
    ###
    ### YOUR CODE HERE
    ###


In [ ]:
# test your result
a = torch.tensor([[1, 2, -3], [2.5, -0.2, 6]])
ReLU(a)

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


## <font color='blue'>2. Softmax Implementation (10 Points)</font>

Softmax is defined as follows:
$$
\text{softmax}(z_{i}) = \frac{\exp(z_i)}{\sum_j \exp(z_j)}
$$

For example, we have following an array as an input:
```
tensor([0.6000, 5.2000, 9.2000])
```

Then, the function should return the following as output:
```
tensor([1.8076e-04, 1.7983e-02, 9.8184e-01])
```

<div class="alert alert-block alert-info">
    <b>2. Softmax Implementation: 10 Points</b>
</div>

In [ ]:
def softmax(array):
    
    ###
    ### YOUR CODE HERE
    ###


In [ ]:
# Test your result
a = torch.tensor([0.6, 5.2, 9.2])
softmax(a)

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


## <font color='blue'>3. Neural Network Neuron Implementation (15 Points)</font>


We all are familiar with the `1-dimensional` linear equation:

$$
y = mx + c
$$

We can re-write the equation as:

$$
y = w_1x + b
$$

We can write the `n-dimensional` linear equation as follows:

$$
y = w_1x_1 + w_2x_2 + ... + w_nx_n + b
$$


Following is a pictorial representation `n-dimensional` linear equations. This linear function is called a neuron in neural networks. 

<img src='https://www.learnopencv.com/wp-content/uploads/2020/01/c3_w1_linear_equation.png'>

let's define $W$ as,
$$
W = \begin{bmatrix}
    w_1       & w_2 & w_3 & \dots & w_n
\end{bmatrix}
$$

and $X$ as,
$$
 X = \begin{bmatrix}
           x_{1} \\
           x_{2} \\
           \vdots \\
           x_{n}
         \end{bmatrix}
$$

Using above $W$ and $X$, we can re-write the n-dimensional linear equation as follows:

$$
y = WX + b
$$

In a neural network, $X$, $W$, $b$, and $y$ are called input, weight, bias, and output of the neuron, respectively. 

In a neural network, usually, we use to have much more than one neuron. The same input $X$ passes through all neurons of the layer and gets output $y$ for each neuron. We don't have to calculate linear function for each neuron at a time; we can calculate all in one go using Numpy.

Let's assume we have `m` neurons. So we will have `m` output. Let's stack all weight horizontally and do matrix multiplication by input and add stacked $b$. It will give `m` output for all `m` neurons. 


$$
W = \begin{bmatrix}
    w_{11}       & w_{12} & w_{13} & \dots & w_{1n} \\
    w_{21}       & w_{22} & w_{23} & \dots & w_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    w_{m1}       & w_{m2} & w_{m3} & \dots & w_{mn}
\end{bmatrix}
$$

$$
 B = \begin{bmatrix}
           b_{1} \\
           b_{2} \\
           \vdots \\
           b_{m}
         \end{bmatrix}
$$

$$
 Y = \begin{bmatrix}
           y_{1} \\
           y_{2} \\
           \vdots \\
           y_{m}
         \end{bmatrix}
$$

You have to implement the following function:
$$
Y = WX + B
$$
The function will take weight $W$, bias $B$, and input $X$ as arguments. You have to return outputs $Y$.

For example, arguments $W$, $B$ and $X$ are as follows:
```
W = tensor([[1.2000, 0.3000, 0.1000],
            [0.0100, 2.1000, 0.7000]])
B = tensor([2.1000, 0.8900])
X = tensor([0.3000, 6.8000, 0.5900])
```

Function should return:
```
tensor([ 4.5590, 15.5860])
```

<div class="alert alert-block alert-info">
    <b>3. Neuron Implementation: 15 Points</b>
</div>

In [ ]:
def neural_network_neurons(W, B, X):
    
    ###
    ### YOUR CODE HERE
    ###


In [ ]:
# test your code
W = torch.tensor([[1.2, 0.3, 0.1], [.01, 2.1, 0.7]])
B = torch.tensor([2.1, 0.89])
X = torch.tensor([0.3, 6.8, 0.59])

neural_network_neurons(W, B, X)

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###
